### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by xtremecreative** [mahaveerverma/hand-gesture-recognition-opencv#10]
while executing the program after pressing b and then c this error is coming

Traceback (most recent call last):
  File "HandRecognition.py", line 207, in <module>
    contours,hierarchy=cv2.findContours(contour_frame,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack

and the bounding boxes being displayed like this as per image bellow

I am very much new to all these things Kindly guide me further

![sc_001](https://user-images.githubusercontent.com/31309532/37251636-e357505e-2539-11e8-9efc-d384cf51c18c.png)

**Comment by jatinparab** [comment]
Seems like you are using opencv version 3+
Change the line 
`contours,hierarchy=cv2.findContours(contour_frame,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
`
 to 
`_ ,contours, hierarchy=cv2.findContours(contour_frame,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
` 
the new findContours function returns 3 values.

**Comment by xtremecreative** [comment]
Thanks sulphurgfx its really solved the problem !!!!
