### ISSUE TITLE
Program run error!

### ISSUE THREAD

**Issue by EricSun787** [mahaveerverma/hand-gesture-recognition-opencv#14]
when i press 'c' to capture hand histogram ,the program returned and display "contours,hierarchy=cv2.findContours(contour_frame,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack." 

Thank you.

**Comment by vrajpal-jhala** [comment]
> when i press 'c' to capture hand histogram ,the program returned and display "contours,hierarchy=cv2.findContours(contour_frame,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
> ValueError: too many values to unpack."
> 
> Thank you.

funtion "cv2.findContours(contour_frame,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)" returns total 3 values, so you have to put 3 variables on the LHS of the assignment

just replace that line with...

_,contours,hierarchy=cv2.findContours(contour_frame,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

**Comment by EricSun787** [comment]
Thank you！
