### ISSUE TITLE
To generate a background model when I press b it exits and error occurs in line 232 ie "bg_model = cv2.BackgroundSubtractorMOG2(0,10) " ie Attribute error: 'module' object has no attribute 'BackgroundSubtractorMOG2' 

### ISSUE THREAD

**Issue by anuvava** [mahaveerverma/hand-gesture-recognition-opencv#2]

**Comment by mahaveerverma** [comment]
Please use OpenCV2.4.8 for this project. Or else you'll have to modify that line for OpenCV3.0 onwards to use cv2.BackgroundSubtractorMOG instead of cv2.BackgroundSubtractorMOG2. Refer the documentation for the same for your specific OpenCV version.

I'd suggest using OpenCV2.4.8 or if you don't want to downgrade from your current OpenCV version, you can use 'virtual environment' and setup OpenCV2.4.8 exclusively for this project there.

**Comment by anuvava** [comment]
Sir I modify the line but the same error occurs.
I already installed opencv 3.0.1 and python 2.7.6 on ubuntu 14.0.1. So Is it possible to install opencv 2.4.8 on system?
How can I use virtual environment and setup opencv2.4.8.?
Is there any problem occur if I use use virtual environment along with the already downloaded version?

**Comment by mahaveerverma** [comment]
I would suggest to use virtual environment. A virtual environment does this exact task of creating a virtual new workspace for your codes in which you can install a different version of any library and it won't affect your existing installations.

Here is a tutorial on using virtualenv: http://docs.python-guide.org/en/latest/dev/virtualenvs/

Here, once you activate your virtual environment, python will be automatically setup in it. Then just install opencv2.4.8 normally in your virtual environment. Installing any packages inside the env won't interfere with any other existing package from the host system.

**Comment by Ankur-prasun** [comment]
change it to cv2.createBackgroundSubtractorMOG2(0,10) and it will work.
for more info run the command  help(cv2) in python console

**Comment by anuvava** [comment]
Sir,
Thanks. It works.But there occurs another error. To capture maximum range
of shades of hand when press c it exit and an error displays.

In line 207
:contours,hierarchy=cv2.findContours(contour_frame,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

"value error:too many values to unpack".

How to resolve this error ?

**Comment by Ankur-prasun** [comment]
Change it to
_,contours,hierarchy=cv2.findContours(contour_frame,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

**Comment by anuvava** [comment]
Sir,

Thanks a lot...

After doing it no error....Well done sir...Again Thanks a lot for your
contribution...

**Comment by Ankur-prasun** [comment]
anuvava
Have you solved the issue of hand gesture dictionary which i have raised?
kindly let me know

**Comment by anuvava** [comment]
I also have the same problem.Gestures not detected properly as shown in the
documentation.

**Comment by mahaveerverma** [comment]
Thanks for the help @Ankur-prasun . And @anuvava, for improving efficiency, I would suggest redefining dictionary definitions. I've tried explaining the part on how to read dimensions in the other 'issue'. Please refer that.

**Comment by anuvava** [comment]
Sir,
Can you publish the modified code for deciding hand radius and finger positions, such that it prints these parameters at all times whenever any hand is shown to it. ..
So that I can recognize the hand radius and finger positions of my hand and modify the dimensions in GestureAPI.py .
Can you please help me sir?

**Comment by anuvava** [comment]
Sir,

I read your documentation.I have some doubts regarding the concepts.

First hand histogram is created.After that whether create a histogram for
frame?
How can we searching for hand using the already histogram generated?
when I add these lines the histogram and contour displayed like this.Is the
displayed histograms and contour is correct?
cv2.imshow('contour', found)
cv2.imshow('histogram', hand_hist)

What are the algorithms or techniques used for contour,convex hull
technically?

**Comment by anuvava** [comment]
Sir,

Can you please explain what method is used to identify the finger tips.?
Can you specify the algorithm used for the fingertip detection.?I refer
many documents.But I could not understand properly.Please reply to this
mail.

**Comment by sweden009** [comment]
line 40, in hand_capture
    for i in xrange(capture_box_count):
NameError: name 'xrange' is not defined


what should i do please help

**Comment by ghost** [comment]
Can you share the link to the whl of openCV 2.4.8 ?

**Comment by guillaumesoul** [comment]
@sweden009 : try change everywhere xrange function is used by range

**Comment by mahaveerverma** [comment]
@amandeepsinghkhanna  You can get the full setup from https://sourceforge.net/projects/opencvlibrary/files/opencv-win/2.4.10/

You need only C:\opencv\build\python\x86\2.4.10\cv2.pyd (the folder structure might be a little different). Copy that to C:\Python27\Lib\site-packages\
