### ISSUE TITLE
ImportError: No module named GestureAPI

### ISSUE THREAD

**Issue by somavardhan** [mahaveerverma/hand-gesture-recognition-opencv#6]
I Like this code as a fresher i installed python opencv with numpy cmake and scipy but when i tried to execute ur code i got this error 

"Traceback (most recent call last):
  File "C:\Python27\hand_gesture", line 4, in <module>
    from GestureAPI import *
ImportError: No module named GestureAPI"

can u help me to solve this problem plz solve it as fast as possible

**Comment by aimxu** [comment]
make sure the python file "GestureAPI.py" is in the same folder with "HandRecognition.py"
